-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.api_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  name text NOT NULL,
  token_hash text NOT NULL,
  prefix text NOT NULL,
  scopes ARRAY DEFAULT ARRAY['review:pr'::text],
  expires_at timestamp with time zone,
  revoked_at timestamp with time zone,
  last_used_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  usage_count integer DEFAULT 0,
  created_ip text,
  created_user_agent text,
  last_used_ip text,
  last_used_user_agent text,
  token_type character varying DEFAULT 'custom'::character varying,
  is_active boolean DEFAULT true,
  CONSTRAINT api_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT api_tokens_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT api_tokens_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid,
  event_type text NOT NULL,
  actor_type text NOT NULL CHECK (actor_type = ANY (ARRAY['user'::text, 'service'::text, 'system'::text])),
  actor_id text,
  resource_type text,
  resource_id text,
  action text,
  details jsonb DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  success boolean DEFAULT true,
  failure_reason text,
  created_at timestamp with time zone DEFAULT now(),
  request_id text,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.chat_interactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  repo_name text NOT NULL,
  pr_number integer NOT NULL,
  command text NOT NULL,
  finding_id uuid,
  question text,
  response text,
  github_user text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT chat_interactions_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT chat_interactions_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES public.findings(id)
);
CREATE TABLE public.finding_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  finding_id uuid,
  org_id uuid NOT NULL,
  fingerprint text NOT NULL,
  repo_name text,
  label text NOT NULL CHECK (label = ANY (ARRAY['true_positive'::text, 'false_positive'::text, 'accepted_risk'::text])),
  comment text,
  created_by uuid,
  created_by_github text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT finding_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT finding_feedback_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES public.findings(id),
  CONSTRAINT finding_feedback_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT finding_feedback_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.finding_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  finding_id uuid NOT NULL,
  org_id uuid NOT NULL,
  old_status text NOT NULL,
  new_status text NOT NULL,
  changed_by_user_id uuid,
  change_method text NOT NULL CHECK (change_method = ANY (ARRAY['automatic'::text, 'manual'::text, 'clean_pr'::text, 'system'::text])),
  reason text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT finding_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT finding_status_history_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES public.findings(id),
  CONSTRAINT finding_status_history_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT finding_status_history_changed_by_user_id_fkey FOREIGN KEY (changed_by_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.findings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  review_id uuid NOT NULL,
  org_id uuid NOT NULL,
  fingerprint text NOT NULL,
  title text NOT NULL,
  risk text NOT NULL CHECK (risk = ANY (ARRAY['HIGH'::text, 'MEDIUM'::text, 'LOW'::text])),
  confidence text NOT NULL CHECK (confidence = ANY (ARRAY['HIGH'::text, 'MEDIUM'::text, 'LOW'::text, 'NEEDS_REVIEW'::text])),
  file_path text,
  line_range text,
  evidence text,
  description text,
  impact text,
  recommendation text,
  example_fix text,
  category text,
  owasp text,
  cwe text,
  is_new boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'resolved'::text, 'accepted_risk'::text, 'false_positive'::text, 'wont_fix'::text])),
  resolution_method text CHECK (resolution_method IS NULL OR (resolution_method = ANY (ARRAY['automatic'::text, 'manual'::text, 'clean_pr'::text]))),
  resolved_by_user_id uuid,
  resolved_reason text,
  resolved_notes text,
  severity text,
  line_start integer,
  line_end integer,
  original_code text,
  suggested_fix text,
  CONSTRAINT findings_pkey PRIMARY KEY (id),
  CONSTRAINT findings_review_id_fkey FOREIGN KEY (review_id) REFERENCES public.reviews(id),
  CONSTRAINT findings_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT findings_resolved_by_user_id_fkey FOREIGN KEY (resolved_by_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.github_app_installations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  installation_id bigint NOT NULL UNIQUE,
  account_login text NOT NULL,
  account_type text NOT NULL CHECK (account_type = ANY (ARRAY['User'::text, 'Organization'::text])),
  account_id bigint NOT NULL,
  repository_selection text DEFAULT 'all'::text,
  permissions jsonb DEFAULT '{}'::jsonb,
  events jsonb DEFAULT '[]'::jsonb,
  installed_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  suspended_at timestamp with time zone,
  suspended_by text,
  CONSTRAINT github_app_installations_pkey PRIMARY KEY (id),
  CONSTRAINT github_app_installations_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.github_connections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  github_user_id bigint NOT NULL,
  github_username text NOT NULL,
  access_token_hash text,
  scopes ARRAY,
  connected_at timestamp with time zone DEFAULT now(),
  last_used_at timestamp with time zone,
  is_active boolean DEFAULT true,
  encrypted_access_token text,
  org_id uuid,
  CONSTRAINT github_connections_pkey PRIMARY KEY (id),
  CONSTRAINT github_connections_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT github_connections_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.gitlab_app_installations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  installation_id text NOT NULL,
  account_login text NOT NULL,
  account_type text NOT NULL,
  account_id bigint NOT NULL,
  gitlab_instance_url text NOT NULL DEFAULT 'https://gitlab.com'::text,
  scopes ARRAY DEFAULT '{}'::text[],
  installed_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  CONSTRAINT gitlab_app_installations_pkey PRIMARY KEY (id),
  CONSTRAINT gitlab_app_installations_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT gitlab_app_installations_org_installation_key UNIQUE (org_id, installation_id)
);
CREATE TABLE public.gitlab_connections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  gitlab_user_id bigint NOT NULL,
  gitlab_username text NOT NULL,
  gitlab_instance_url text NOT NULL DEFAULT 'https://gitlab.com'::text,
  access_token_hash text,
  scopes ARRAY,
  connected_at timestamp with time zone DEFAULT now(),
  last_used_at timestamp with time zone,
  is_active boolean DEFAULT true,
  encrypted_access_token text,
  org_id uuid,
  CONSTRAINT gitlab_connections_pkey PRIMARY KEY (id),
  CONSTRAINT gitlab_connections_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT gitlab_connections_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.gitlab_webhook_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  action text,
  repo_name text NOT NULL,
  mr_number integer,
  org_id uuid,
  installation_id text,
  status text NOT NULL CHECK (status = ANY (ARRAY['received'::text, 'processing'::text, 'completed'::text, 'error'::text, 'skipped'::text])),
  error_message text,
  review_id uuid,
  processing_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gitlab_webhook_events_pkey PRIMARY KEY (id),
  CONSTRAINT gitlab_webhook_events_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT gitlab_webhook_events_review_id_fkey FOREIGN KEY (review_id) REFERENCES public.reviews(id)
);
CREATE TABLE public.github_webhook_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  action text,
  repo_name text NOT NULL,
  pr_number integer,
  org_id uuid,
  installation_id bigint,
  status text NOT NULL CHECK (status = ANY (ARRAY['received'::text, 'processing'::text, 'completed'::text, 'error'::text, 'skipped'::text])),
  error_message text,
  review_id uuid,
  processing_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT github_webhook_events_pkey PRIMARY KEY (id),
  CONSTRAINT github_webhook_events_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT github_webhook_events_review_id_fkey FOREIGN KEY (review_id) REFERENCES public.reviews(id)
);
CREATE TABLE public.oauth_states (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  state_hash text NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '00:10:00'::interval),
  used boolean DEFAULT false,
  CONSTRAINT oauth_states_pkey PRIMARY KEY (id),
  CONSTRAINT oauth_states_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.org_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  email text NOT NULL,
  role text DEFAULT 'member'::text CHECK (role = ANY (ARRAY['admin'::text, 'member'::text])),
  invited_by uuid NOT NULL,
  invite_token text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '7 days'::interval),
  accepted_at timestamp with time zone,
  revoked_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT org_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT org_invitations_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT org_invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.org_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text DEFAULT 'member'::text CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT org_members_pkey PRIMARY KEY (id),
  CONSTRAINT org_members_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT org_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  settings jsonb DEFAULT '{}'::jsonb,
  plan_id text DEFAULT 'free'::text,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.pricing_plans(id)
);
CREATE TABLE public.pricing_plans (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  price_monthly_cents integer DEFAULT 0,
  price_yearly_cents integer DEFAULT 0,
  max_repos integer DEFAULT 1,
  max_prs_per_month integer DEFAULT 30,
  max_team_members integer DEFAULT 1,
  feature_advisory_mode boolean DEFAULT true,
  feature_enforcement_mode boolean DEFAULT false,
  feature_dashboard boolean DEFAULT false,
  feature_audit_logs boolean DEFAULT false,
  feature_sso boolean DEFAULT false,
  feature_policy_as_code boolean DEFAULT false,
  feature_siem_integration boolean DEFAULT false,
  feature_custom_rules boolean DEFAULT false,
  feature_priority_support boolean DEFAULT false,
  feature_dedicated_support boolean DEFAULT false,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pricing_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.repo_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  repo_name text NOT NULL,
  policy jsonb DEFAULT '{"mode": "advisory", "rules": {"auth": true, "ssrf": true, "crypto": true, "secrets": true, "injection": true, "deserialization": true}, "fail_on": "HIGH", "min_risk": "LOW", "blocklist": [], "max_findings": 10, "min_confidence": "LOW"}'::jsonb,
  enabled boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  github_repo_id character varying,
  source character varying DEFAULT 'manual'::character varying CHECK (source::text = ANY (ARRAY['github'::character varying, 'gitlab'::character varying, 'manual'::character varying]::text[])),
  CONSTRAINT repo_configs_pkey PRIMARY KEY (id),
  CONSTRAINT repo_configs_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  repo_name text NOT NULL,
  pr_number integer NOT NULL,
  pr_title text,
  pr_author text,
  review_time_ms integer,
  findings_count integer DEFAULT 0,
  high_count integer DEFAULT 0,
  medium_count integer DEFAULT 0,
  low_count integer DEFAULT 0,
  needs_review_count integer DEFAULT 0,
  success boolean DEFAULT true,
  error_type text,
  should_block boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  previous_review_id uuid,
  new_findings_count integer DEFAULT 0,
  resolved_findings_count integer DEFAULT 0,
  still_present_count integer DEFAULT 0,
  active_findings_count integer DEFAULT 0,
  active_high_count integer DEFAULT 0,
  active_medium_count integer DEFAULT 0,
  active_low_count integer DEFAULT 0,
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT reviews_previous_review_id_fkey FOREIGN KEY (previous_review_id) REFERENCES public.reviews(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL UNIQUE,
  plan_id text NOT NULL DEFAULT 'free'::text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'past_due'::text, 'canceled'::text, 'trialing'::text])),
  billing_cycle text DEFAULT 'monthly'::text CHECK (billing_cycle = ANY (ARRAY['monthly'::text, 'yearly'::text])),
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  trial_end timestamp with time zone,
  canceled_at timestamp with time zone,
  external_customer_id text,
  external_subscription_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  stripe_subscription_id text,
  stripe_customer_id text,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.pricing_plans(id)
);
CREATE TABLE public.suppression_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  fingerprint text,
  title_pattern text,
  file_pattern text,
  category text,
  reason text NOT NULL,
  is_active boolean DEFAULT true,
  expires_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT suppression_rules_pkey PRIMARY KEY (id),
  CONSTRAINT suppression_rules_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT suppression_rules_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.usage_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  repos_count integer DEFAULT 0,
  prs_reviewed integer DEFAULT 0,
  findings_count integer DEFAULT 0,
  team_members_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT usage_records_pkey PRIMARY KEY (id),
  CONSTRAINT usage_records_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);